In [2]:
l = [23245, 27, 546, 215, -1234]

In [3]:
l

[23245, 27, 546, 215, -1234]

In [4]:
import numpy as np

In [6]:
a = np.array(l)

In [7]:
a

array([23245,    27,   546,   215, -1234])

In [8]:
b = np.array([12, 455, 63.3, True, "abc"])

In [9]:
b

array(['12', '455', '63.3', 'True', 'abc'], 
      dtype='<U32')

In [10]:
print(b)

['12' '455' '63.3' 'True' 'abc']


In [11]:
l.pop()

-1234

In [12]:
l

[23245, 27, 546, 215]

In [13]:
# The .pop is a function inside a list, in the above case it could pop off the last value

In [14]:
# Arrays can do the same but they can do many more functions/methods compared to a list

In [15]:
a.mean()

4559.8000000000002

In [16]:
# The above calculated the mean in the array from output 7 (must be numbers)

In [22]:
a.max()

23245

In [23]:
l

[23245, 27, 546, 215]

In [24]:
# Slicing arrays

In [25]:
a

array([23245,    27,   546,   215, -1234])

In [26]:
a[2:]

array([  546,   215, -1234])

In [27]:
a[2:4]

array([546, 215])

In [28]:
# When slicing arrays, this does not create a copy!! This is different to lists which does create a copy. Important to know this

In [29]:
a

array([23245,    27,   546,   215, -1234])

In [30]:
b

array(['12', '455', '63.3', 'True', 'abc'], 
      dtype='<U32')

In [32]:
b[0]

'12'

In [33]:
b = a[2:4]

In [34]:
b

array([546, 215])

In [35]:
b[0]

546

In [36]:
b[:] = 111

In [37]:
b

array([111, 111])

In [38]:
a

array([23245,    27,   111,   111, -1234])

In [39]:
# The values of 'a' have now been replaced from the modification of 'b' above

In [40]:
c = a.copy()

In [41]:
c

array([23245,    27,   111,   111, -1234])

In [42]:
# The copy function is how to make a copy of an array as above

In [43]:
c[0] = 0

In [44]:
c

array([    0,    27,   111,   111, -1234])

In [45]:
a

array([23245,    27,   111,   111, -1234])

In [ ]:
# We can see that we have modified c but not a 