In [1]:
#Data 
revenue = [14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97, 15433.50]
expenses = [12051.82, 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96]

In [2]:
import numpy as np

In [3]:
r = np.array(revenue)

In [4]:
e = np.array(expenses)

In [5]:
r

array([ 14574.49,   7606.46,   8611.41,   9175.41,   8058.65,   8105.44,
        11496.28,   9766.09,  10305.32,  14379.96,  10713.97,  15433.5 ])

In [6]:
e

array([ 12051.82,   5695.07,  12319.2 ,  12089.72,   8658.57,    840.2 ,
         3285.73,   5821.12,   6976.93,  16618.61,  10054.37,   3803.96])

In [10]:
r[:1]

array([ 14574.49])

In [16]:
jan_profit = r[:1] - e[:1]

In [17]:
jan_profit

array([ 2522.67])

In [29]:
jan_after_tax_profit = jan_profit * 0.7

In [30]:
jan_after_tax_profit

array([ 1765.869])

In [35]:
jan_profit_margin = jan_after_tax_profit / e[:1]

In [36]:
jan_profit_margin

array([ 0.14652301])

In [27]:
feb_profit = r[1:2] - e[1:2]

In [28]:
feb_profit

array([ 1911.39])

In [45]:
print(jan_profit, "Jan Profit")

[ 2522.67] Jan Profit


In [46]:
r.mean()

10685.581666666667

In [47]:
r.min()

7606.46

In [49]:
r.max()

15433.5

In [55]:
r.round()

array([ 14574.,   7606.,   8611.,   9175.,   8059.,   8105.,  11496.,
         9766.,  10305.,  14380.,  10714.,  15434.])

In [58]:
rr = r.copy()

In [59]:
rr

array([ 14574.49,   7606.46,   8611.41,   9175.41,   8058.65,   8105.44,
        11496.28,   9766.09,  10305.32,  14379.96,  10713.97,  15433.5 ])

In [60]:
ee = e.copy()

In [63]:
profit = rr - ee

In [64]:
profit

array([  2522.67,   1911.39,  -3707.79,  -2914.31,   -599.92,   7265.24,
         8210.55,   3944.97,   3328.39,  -2238.65,    659.6 ,  11629.54])

In [65]:
profit_after_tax = profit * 0.7

In [66]:
profit_after_tax

array([ 1765.869,  1337.973, -2595.453, -2040.017,  -419.944,  5085.668,
        5747.385,  2761.479,  2329.873, -1567.055,   461.72 ,  8140.678])

In [67]:
profit_margin = profit_after_tax / rr

In [68]:
profit_margin

array([ 0.12116163,  0.17589956, -0.30139698, -0.22233524, -0.05211096,
        0.62743886,  0.49993433,  0.28276199,  0.22608449, -0.10897492,
        0.04309514,  0.52746804])

In [69]:
profit_after_tax.mean()

1750.6813333333332

In [70]:
profit_after_tax > profit_after_tax.mean()

array([ True, False, False, False, False,  True,  True,  True,  True,
       False, False,  True], dtype=bool)

In [71]:
profit_after_tax < profit_after_tax.mean()

array([False,  True,  True,  True,  True, False, False, False, False,
        True,  True, False], dtype=bool)

In [72]:
profit_after_tax.max()

8140.6779999999999

In [83]:
profit_after_tax.round()

array([ 1766.,  1338., -2595., -2040.,  -420.,  5086.,  5747.,  2761.,
        2330., -1567.,   462.,  8141.])

In [76]:
profit_after_tax.min()

-2595.4530000000004

In [84]:
print(profit_margin)

[ 0.12116163  0.17589956 -0.30139698 -0.22233524 -0.05211096  0.62743886
  0.49993433  0.28276199  0.22608449 -0.10897492  0.04309514  0.52746804]
